import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTheme } from '../../context/ThemeContext';
import { useProjects } from '../../hooks/useProjects';
import { useTasks } from '../../hooks/useTasks';
import { useAgents } from '../../hooks/useAgents';
import { useToast } from '../../context/ToastContext';
import TaskModal from './TaskModal';
import './ProjectDetailsPage.css';
import '../dashboard/TaskBoard.css'; // Sync Tasks Dashboard style


/* ── No columns config needed, using TaskBoard structure ── */

/* ══════════════════════════════════════════════════════
   PROJECT DETAILS PAGE  (Kanban Task Board)
══════════════════════════════════════════════════════ */
const ProjectDetailsPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { theme } = useTheme();
  const isDark = theme === 'dark';
  const toast = useToast();

  const { projects, loadProjects } = useProjects();
  const { tasks, loading, error, loadTasks, addTask, editTaskContent, removeTask, getGroupedTasks } = useTasks();
  const { loadingMap, resultsMap, errorMap, executeAgent } = useAgents();

  const [project, setProject] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingTask, setEditingTask] = useState(null);
  const [taskToDelete, setTaskToDelete] = useState(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [activeTab, setActiveTab] = useState('tasks');
  const [pipelineState, setPipelineState] = useState({ status: 'idle', logs: [], complete: false });

  /* Load project info */
  useEffect(() => {
    if (projects.length === 0) loadProjects();
    else {
      const found = projects.find(p => p._id === id || p.id === id);
      if (found) setProject(found);
    }
  }, [id, projects, loadProjects]);

  /* Load tasks */
  useEffect(() => { if (id) loadTasks(id); }, [id, loadTasks]);

  /* Handlers */
  const handleSaveTask = async (taskData) => {
    try {
      if (editingTask) {
        await editTaskContent(editingTask._id || editingTask.id, taskData);
        toast.success('Task updated');
      } else {
        await addTask(taskData);
        toast.success('Task created');
      }
    } catch (err) {
      toast.error(err.message || 'Failed to save task');
      throw err;
    }
  };

  const confirmDelete = async () => {
    if (!taskToDelete) return;
    setIsDeleting(true);
    try {
      await removeTask(taskToDelete._id || taskToDelete.id);
      toast.success(`"${taskToDelete.title}" deleted`);
      setTaskToDelete(null);
    } catch (err) { toast.error(err.message || 'Delete failed'); }
    finally { setIsDeleting(false); }
  };

  const handleRunPlanner = async () => {
    // Reset and start pipeline
    setPipelineState({ status: 'running', logs: ['[i] Initializing AI Engine...'], complete: false });
    
    try {
      // Small simulated delay for effect
      await new Promise(resolve => setTimeout(resolve, 800));
      setPipelineState(prev => ({ ...prev, logs: [...prev.logs, '[⟳] Analyzing Project Scope and Objectives...'] }));

      const result = await executeAgent('planner', {
        projectId: id,
        description: project?.description || 'Build AI autonomous project manager'
      });
      
      const generatedTasks = result?.data?.tasks?.tasks || result?.tasks?.tasks || [];
      const generatedPlan = result?.data?.planner?.plan || result?.planner?.plan || [];
      
      setPipelineState(prev => ({ ...prev, logs: [...prev.logs, `[✔] Strategic Plan Generated: ${generatedPlan.length} overarching steps.`] }));
      
      if (generatedTasks.length > 0) {
        setPipelineState(prev => ({ ...prev, logs: [...prev.logs, `[⟳] Provisioning ${generatedTasks.length} tasks into Kanban pipeline...`] }));
        
        // Loop sequentially to show step-by-step insertion
        for (let i = 0; i < generatedTasks.length; i++) {
          const taskTitle = generatedTasks[i];
          const shortTitle = taskTitle.length > 40 ? taskTitle.substring(0, 40) + '...' : taskTitle;
          
          setPipelineState(prev => ({ ...prev, logs: [...prev.logs, `[-] Provisioning: ${shortTitle}`] }));
          
          await addTask({
            title: taskTitle,
            description: 'Autonomously generated by AI Planner Agent based on project scope.',
            status: 'todo',
            project: id
          });
          
          // Tiny delay to make the terminal output feel "real"
          await new Promise(resolve => setTimeout(resolve, 600));
        }
        
        setPipelineState(prev => ({ 
          status: 'complete', 
          complete: true,
          logs: [...prev.logs, '[✔] Provisioning Complete!', '[★] Workflow Automation Finished. You can now view your tasks on the Kanban Board.'] 
        }));
        toast.success('AI Workflow deployed successfully!');
        
      } else {
        setPipelineState(prev => ({ 
          status: 'complete', 
          complete: true,
          logs: [...prev.logs, '[!] AI Engine generated a plan but found zero strict tasks to provision.', '[★] Workflow Finished.'] 
        }));
      }
      
    } catch (err) {
      setPipelineState(prev => ({ 
        status: 'error', 
        complete: true,
        logs: [...prev.logs, `[✖] FATAL ERROR: ${err.message || 'Pipeline failed during execution'}`] 
      }));
      toast.error('Workflow failed');
    }
  };

  const groupedTasks = getGroupedTasks();
  const todoTasks = groupedTasks['pending'] || [];
  const inProgressTasks = groupedTasks['in-progress'] || [];
  const reviewTasks = groupedTasks['completed'] || [];
  const totalTasks = (tasks || []).length;

  /* ── Tab styles ────────────────────────────────── */
  const tabBase = {
    padding: '0.6rem 0',
    fontSize: '0.82rem',
    fontWeight: 600,
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    transition: 'all 0.2s',
  };
  const tabActive = (color) => ({ ...tabBase, borderBottomColor: color, color });
  const tabInactive = { ...tabBase, color: isDark ? '#6b7280' : '#9ca3af' };

  /* ── Not Found ─────────────────────────────────── */
  if (!project && projects.length > 0) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '50vh' }}>
        <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: isDark ? '#d1d5db' : '#374151' }}>Project Not Found</h2>
        <button onClick={() => navigate('/projects')} style={{
          marginTop: '1rem', padding: '0.5rem 1.25rem', background: 'rgba(59,130,246,0.1)',
          color: '#3b82f6', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, fontSize: '0.85rem',
        }}>Back to Projects</button>
      </div>
    );
  }

  /* ── Render ────────────────────────────────────── */
  return (
    <div className="pd-page" style={{ animation: 'pdFadeIn 0.3s ease both' }}>

      {/* ─── Back button ────────────────────────── */}
      <button
        onClick={() => navigate('/projects')}
        className="pd-back-btn"
        style={{ color: isDark ? '#9ca3af' : '#6b7280' }}
      >
        <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
        </svg>
        Back to Projects
      </button>

      {/* ─── Project Header Card ────────────────── */}
      <div className="pd-header-card">
        <div className="pd-header-info">
          <h1 className="pd-title">
            {project ? project.name : 'Loading…'}
          </h1>
          <p className="pd-desc">
            {project?.description || 'No description provided.'}
          </p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          {activeTab === 'tasks' && (
            <button
              onClick={() => { setEditingTask(null); setIsModalOpen(true); }}
              className="pd-add-task-btn"
            >
              <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
              </svg>
              Add Task
            </button>
          )}
        </div>
      </div>

      {/* ─── Tabs ───────────────────────────────── */}
      <div className="pd-tabs">
        <button onClick={() => setActiveTab('tasks')} style={activeTab === 'tasks' ? tabActive('#3b82f6') : tabInactive}>
          <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
          Kanban Board
          <span className="pd-tab-count" style={{
            background: activeTab === 'tasks' ? 'rgba(59,130,246,0.12)' : (isDark ? '#374151' : '#f3f4f6'),
            color: activeTab === 'tasks' ? '#3b82f6' : '#9ca3af',
          }}>{totalTasks}</span>
        </button>
        <button onClick={() => setActiveTab('ai')} style={activeTab === 'ai' ? tabActive('#8b5cf6') : tabInactive}>
          <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
          AI Workspace
        </button>
        <button onClick={() => setActiveTab('reports')} style={activeTab === 'reports' ? tabActive('#10b981') : tabInactive}>
          <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Reports
        </button>
      </div>

      {/* ─── Tab Content ────────────────────────── */}
      {activeTab === 'ai' ? (
        <div style={{ marginTop: '1.5rem', animation: 'pdFadeIn 0.3s ease both' }}>
          
          {pipelineState.status !== 'idle' ? (
            /* CI/CD Pipeline Terminal View */
            <div className="ci-pipeline-container" style={{
              background: isDark ? '#0d1117' : '#1e293b',
              border: `1px solid ${isDark ? '#30363d' : '#334155'}`,
              borderRadius: '12px', overflow: 'hidden', boxShadow: '0 10px 30px rgba(0,0,0,0.2)'
            }}>
              {/* Terminal Header */}
              <div style={{
                background: isDark ? '#161b22' : '#0f172a', borderBottom: `1px solid ${isDark ? '#30363d' : '#334155'}`,
                padding: '0.75rem 1.25rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <div style={{ display: 'flex', gap: '6px' }}>
                    <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#ef4444' }}></div>
                    <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#f59e0b' }}></div>
                    <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#10b981' }}></div>
                  </div>
                  <span style={{ color: '#9ca3af', fontSize: '0.8rem', fontWeight: 600, marginLeft: '0.75rem', fontFamily: 'monospace' }}>
                    Agent_Pipeline_Deploy
                  </span>
                </div>
                {pipelineState.status === 'running' && (
                  <span style={{ color: '#3b82f6', fontSize: '0.75rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <span className="pd-spinner" style={{ width: 12, height: 12, borderWidth: 2 }}></span> Running
                  </span>
                )}
                {pipelineState.status === 'complete' && (
                  <span style={{ color: '#10b981', fontSize: '0.75rem', fontWeight: 700 }}>SUCCESS</span>
                )}
                {pipelineState.status === 'error' && (
                  <span style={{ color: '#ef4444', fontSize: '0.75rem', fontWeight: 700 }}>FAILED</span>
                )}
              </div>

              {/* Terminal Logs */}
              <div style={{ padding: '1.5rem', fontFamily: 'monospace', fontSize: '0.85rem', color: '#e2e8f0', minHeight: '300px', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                {pipelineState.logs.map((log, index) => {
                  let logColor = '#e2e8f0';
                  if (log.includes('[✔]') || log.includes('[★]')) logColor = '#10b981';
                  if (log.includes('[✖]') || log.includes('FATAL ERROR')) logColor = '#ef4444';
                  if (log.includes('[⟳]')) logColor = '#3b82f6';
                  if (log.includes('[i]')) logColor = '#8b5cf6';
                  if (log.includes('[-] Provisioning:')) logColor = '#f59e0b';
                  
                  return (
                    <div key={index} style={{ color: logColor, animation: 'pdFadeIn 0.2s ease-out' }}>
                      <span style={{ opacity: 0.5, marginRight: '0.75rem' }}>{(index + 1).toString().padStart(2, '0')}:</span>
                      {log}
                    </div>
                  );
                })}
                
                {pipelineState.status === 'running' && (
                  <div style={{ color: '#9ca3af', marginTop: '0.5rem', animation: 'pulse 1.5s infinite' }}>_</div>
                )}
              </div>

              {/* Actions */}
              {pipelineState.complete && (
                <div style={{ padding: '1.25rem 1.5rem', background: isDark ? '#161b22' : '#0f172a', borderTop: `1px solid ${isDark ? '#30363d' : '#334155'}`, display: 'flex', justifyContent: 'flex-end', gap: '1rem' }}>
                  <button onClick={() => setPipelineState({ status: 'idle', logs: [], complete: false })} style={{
                    padding: '0.5rem 1rem', background: 'transparent', color: '#9ca3af', border: '1px solid #4b5563', borderRadius: '6px', fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'monospace'
                  }}>Reset Pipeline</button>
                  {pipelineState.status === 'complete' && (
                    <button onClick={() => setActiveTab('tasks')} style={{
                      padding: '0.5rem 1rem', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '6px', fontSize: '0.8rem', fontWeight: 700, cursor: 'pointer', fontFamily: 'monospace'
                    }}>View Kanban Board &rarr;</button>
                  )}
                </div>
              )}
            </div>
            
          ) : (
            <div style={{
              padding: '3rem 2rem', textAlign: 'center', borderRadius: '14px',
              background: isDark ? '#1f2937' : '#f9fafb',
              border: `1px dashed ${isDark ? '#4b5563' : '#d1d5db'}`,
              display: 'flex', flexDirection: 'column', alignItems: 'center'
            }}>
              <div style={{
                width: '64px', height: '64px', borderRadius: '16px',
                background: 'linear-gradient(135deg, rgba(139,92,246,0.2), rgba(59,130,246,0.2))',
                display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1.25rem'
              }}>
                <svg width="32" height="32" fill="none" viewBox="0 0 24 24" stroke="#8b5cf6">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: isDark ? '#f9fafb' : '#111827', marginBottom: '0.5rem' }}>AI Project Planner</h3>
              <p style={{ fontSize: '0.85rem', color: '#9ca3af', maxWidth: '420px', lineHeight: 1.6, marginBottom: '2rem' }}>
                Leverage our autonomous AI agent to analyze your project description and instantly orchestrate a master development timeline, feature breakdown, and actionable task backlog.
              </p>
              <button
                onClick={handleRunPlanner}
                style={{
                  padding: '0.75rem 1.75rem',
                  background: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
                  color: '#fff', border: 'none', borderRadius: '10px',
                  fontSize: '0.9rem', fontWeight: 700, cursor: 'pointer',
                  boxShadow: '0 4px 14px rgba(139, 92, 246, 0.4)',
                  display: 'flex', alignItems: 'center', gap: '0.5rem',
                  transition: 'transform 0.2s, box-shadow 0.2s'
                }}
                onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 6px 20px rgba(139, 92, 246, 0.5)'; }}
                onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 4px 14px rgba(139, 92, 246, 0.4)'; }}
              >
                <svg width="18" height="18" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Run Planner Agent
              </button>
            </div>
          )}
        </div>
      ) : activeTab === 'reports' ? (
        <div style={{
          padding: '2.5rem', textAlign: 'center', borderRadius: '14px',
          background: isDark ? '#1f2937' : '#f9fafb',
          border: `1px dashed ${isDark ? '#374151' : '#d1d5db'}`,
        }}>
          <svg width="40" height="40" fill="none" viewBox="0 0 24 24" stroke="#10b981" style={{ margin: '0 auto 0.75rem' }}>
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, color: isDark ? '#f9fafb' : '#111827' }}>Project Reports</h3>
          <p style={{ fontSize: '0.82rem', color: '#9ca3af', marginTop: '0.25rem' }}>
            Go to the <button onClick={() => navigate('/reports')} style={{ color: '#3b82f6', cursor: 'pointer', background: 'none', border: 'none', textDecoration: 'underline', fontWeight: 600, fontSize: 'inherit' }}>Reports page</button> to submit and view project reports.
          </p>
        </div>
      ) : (
        /* ─── Kanban Task Board ──────────────────── */
        <>
          {loading && (tasks || []).length === 0 ? (
            <div style={{ display: 'flex', justifyContent: 'center', padding: '3rem 0' }}>
              <div className="pd-spinner-lg" />
            </div>
          ) : error ? (
            <div style={{
              maxWidth: 460, margin: '2rem auto', padding: '1.5rem',
              background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.2)',
              borderRadius: '14px', textAlign: 'center',
            }}>
              <p style={{ color: '#ef4444', fontWeight: 600, marginBottom: '0.5rem' }}>Failed to load tasks</p>
              <p style={{ color: '#9ca3af', fontSize: '0.82rem', marginBottom: '1rem' }}>{error}</p>
              <button onClick={() => loadTasks(id)} style={{
                padding: '0.5rem 1.25rem', background: '#ef4444', color: '#fff',
                border: 'none', borderRadius: '8px', fontSize: '0.82rem', fontWeight: 600, cursor: 'pointer',
              }}>Retry</button>
            </div>
          ) : (
            <div className="kanban-scroll-container" style={{ marginTop: '1.5rem', height: '100%' }}>
              {/* TO-DO COLUMN */}
              <div className="kanban-column">
                <div className="column-header">
                  <h3>To-Do <span className="count">{todoTasks.length}</span></h3>
                  <button className="add-btn" onClick={() => { setEditingTask(null); setIsModalOpen(true); }} aria-label="Add Task">
                    <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                  </button>
                </div>
                
                <div className="kanban-cards">
                  {todoTasks.map((task) => (
                    <div key={task._id || task.id} className="task-card">
                      <span className="badge bd-orange outline">Priority</span>
                      <button className="options-btn" onClick={() => { setEditingTask(task); setIsModalOpen(true); }} aria-label="Options">
                        <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"/></svg>
                      </button>
                      <h4>{task.title}</h4>
                      <p className="card-desc">{task.description}</p>
                      
                      <div className="card-footer">
                        <div className="card-actions">
                          <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"/></svg>
                        </div>
                        <div className="avatars small">
                          <div className="avatar outline"></div>
                        </div>
                      </div>
                    </div>
                  ))}
                  <button className="add-task-btn" onClick={() => { setEditingTask(null); setIsModalOpen(true); }}>
                    <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                    Add New Task
                  </button>
                </div>
              </div>

              {/* IN PROGRESS COLUMN */}
              <div className="kanban-column">
                <div className="column-header">
                  <h3>In Progress <span className="count bg-blue">{inProgressTasks.length}</span></h3>
                  <button className="add-btn" onClick={() => { setEditingTask(null); setIsModalOpen(true); }} aria-label="Add Task">
                    <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                  </button>
                </div>
                
                <div className="kanban-cards">
                  {inProgressTasks.map((task) => (
                    <div key={task._id || task.id} className="task-card">
                      <span className="badge bd-orange outline">Priority</span>
                      <button className="options-btn" onClick={() => { setEditingTask(task); setIsModalOpen(true); }} aria-label="Options">
                        <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"/></svg>
                      </button>
                      <h4>{task.title}</h4>
                      <p className="card-desc">{task.description}</p>
                      
                      <div className="card-footer space-between mt-override">
                        <div className="card-actions">
                          <span className="due-date">
                            <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
                          </span>
                        </div>
                        <div className="avatars small">
                          <div className="avatar blue"></div>
                        </div>
                      </div>
                    </div>
                  ))}
                  <button className="add-task-btn" onClick={() => { setEditingTask(null); setIsModalOpen(true); }}>
                    <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                    Add New Task
                  </button>
                </div>
              </div>

              {/* REVIEW COLUMN */}
              <div className="kanban-column">
                <div className="column-header">
                  <h3>Review <span className="count">{reviewTasks.length}</span></h3>
                  <button className="add-btn" onClick={() => { setEditingTask(null); setIsModalOpen(true); }} aria-label="Add Task">
                    <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                  </button>
                </div>
                
                <div className="kanban-cards">
                  {reviewTasks.map((task) => (
                    <div key={task._id || task.id} className="task-card">
                      <span className="badge bd-orange outline">Priority</span>
                      <button className="options-btn" onClick={() => { setEditingTask(task); setIsModalOpen(true); }} aria-label="Options">
                        <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"/></svg>
                      </button>
                      <h4>{task.title}</h4>
                      <p className="card-desc">{task.description}</p>
                      
                      <div className="card-footer">
                        <div className="card-actions">
                          <span className="due-date">
                            <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
                          </span>
                        </div>
                        <div className="avatars small">
                          <div className="avatar outline"></div>
                        </div>
                      </div>
                    </div>
                  ))}
                  <button className="add-task-btn" onClick={() => { setEditingTask(null); setIsModalOpen(true); }}>
                    <svg width="18" height="18" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                    Add New Task
                  </button>
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {/* ─── Task Modal ────────────────────────── */}
      {isModalOpen && (
        <TaskModal
          isOpen={isModalOpen}
          task={editingTask}
          projectId={id}
          onClose={() => setIsModalOpen(false)}
          onSave={handleSaveTask}
        />
      )}

      {/* ─── Delete Confirmation ───────────────── */}
      {taskToDelete && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 60,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)',
        }}>
          <div style={{
            background: isDark ? '#1f2937' : '#ffffff',
            borderRadius: '16px', padding: '1.75rem', width: '100%', maxWidth: '380px',
            textAlign: 'center', boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
          }}>
            <div style={{
              width: '44px', height: '44px', borderRadius: '50%', background: 'rgba(239,68,68,0.1)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1rem',
            }}>
              <svg width="22" height="22" fill="none" viewBox="0 0 24 24" stroke="#ef4444">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700, color: isDark ? '#f9fafb' : '#111827', marginBottom: '0.375rem' }}>Delete Task</h3>
            <p style={{ fontSize: '0.85rem', color: '#9ca3af', marginBottom: '1.5rem' }}>
              Delete <strong style={{ color: isDark ? '#f9fafb' : '#111827' }}>"{taskToDelete.title}"</strong>? This cannot be undone.
            </p>
            <div style={{ display: 'flex', justifyContent: 'center', gap: '0.625rem' }}>
              <button onClick={() => setTaskToDelete(null)} disabled={isDeleting} style={{
                padding: '0.5rem 1.25rem', borderRadius: '8px',
                border: `1px solid ${isDark ? '#374151' : '#e5e7eb'}`,
                background: 'transparent', color: isDark ? '#9ca3af' : '#6b7280',
                fontSize: '0.82rem', fontWeight: 500, cursor: 'pointer',
              }}>Cancel</button>
              <button onClick={confirmDelete} disabled={isDeleting} style={{
                padding: '0.5rem 1.25rem', borderRadius: '8px',
                border: 'none', background: '#ef4444', color: '#fff',
                fontSize: '0.82rem', fontWeight: 600, cursor: 'pointer',
                opacity: isDeleting ? 0.6 : 1,
              }}>{isDeleting ? 'Deleting...' : 'Delete'}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProjectDetailsPage;
