/**
 * Centralized API Test Service
 * Covers: Auth, Project, Task, Agent, Engine, Report, Health
 *
 * Each test returns: { module, action, success, data, error, duration }
 * runAllTests(opts) runs sequentially and supports stopOnFailure option.
 */

import apiClient from '../index.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

const makeResult = (module, action, success, data = null, error = null, duration = 0) => ({
  module,
  action,
  success,
  data,
  error,
  duration,
});

const timed = async (fn) => {
  const start = performance.now();
  const result = await fn();
  const duration = Math.round(performance.now() - start);
  return { ...result, duration };
};

// Store shared IDs across tests
let sharedToken = null;
let sharedProjectId = null;
let sharedTaskId = null;

// ─── Test Credentials ─────────────────────────────────────────────────────────
// Configurable — override before calling runAllTests() if needed
export const testCredentials = {
  name: 'Test User',
  email: 'testuser_auto@example.com',
  password: 'Test@12345',
};

// ─── Health Check ─────────────────────────────────────────────────────────────

export const testHealth = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.get('/health');
      return makeResult('system', 'health', true, data);
    } catch (err) {
      return makeResult('system', 'health', false, null, err.message);
    }
  });

// ─── Auth Module ──────────────────────────────────────────────────────────────

export const testRegister = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.post('/auth/register', testCredentials);
      return makeResult('auth', 'register', true, data);
    } catch (err) {
      // 409 Conflict = already registered, treat as acceptable
      const isKnown = err.message?.includes('already') || err.message?.includes('exists');
      return makeResult('auth', 'register', isKnown, null, err.message);
    }
  });

export const testLogin = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.post('/auth/login', {
        email: testCredentials.email,
        password: testCredentials.password,
      });
      const token = data.token || data.accessToken;
      if (token) {
        sharedToken = token;
        localStorage.setItem('token', token);
      }
      const valid = !!token && typeof token === 'string' && token.split('.').length === 3;
      return makeResult('auth', 'login', valid, { token: token?.slice(0, 20) + '…', valid });
    } catch (err) {
      return makeResult('auth', 'login', false, null, err.message);
    }
  });

export const testForgotPassword = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.post('/auth/forgot-password', { email: testCredentials.email });
      return makeResult('auth', 'forgotPassword', true, data);
    } catch (err) {
      return makeResult('auth', 'forgotPassword', false, null, err.message);
    }
  });

// ─── Project Module ───────────────────────────────────────────────────────────

export const testCreateProject = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.post('/projects', {
        name: `[AUTO-TEST] Project ${Date.now()}`,
        description: 'Auto-generated by test service',
      });
      sharedProjectId = data._id || data.id;
      return makeResult('project', 'create', true, { id: sharedProjectId, name: data.name });
    } catch (err) {
      return makeResult('project', 'create', false, null, err.message);
    }
  });

export const testGetProjects = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.get('/projects');
      const count = Array.isArray(data) ? data.length : (data.projects?.length ?? '?');
      return makeResult('project', 'getAll', true, { count });
    } catch (err) {
      return makeResult('project', 'getAll', false, null, err.message);
    }
  });

export const testGetSingleProject = async () =>
  timed(async () => {
    if (!sharedProjectId) return makeResult('project', 'getOne', false, null, 'No project ID — create test skipped or failed');
    try {
      const { data } = await apiClient.get(`/projects/${sharedProjectId}`);
      return makeResult('project', 'getOne', true, { id: data._id || data.id });
    } catch (err) {
      return makeResult('project', 'getOne', false, null, err.message);
    }
  });

export const testUpdateProject = async () =>
  timed(async () => {
    if (!sharedProjectId) return makeResult('project', 'update', false, null, 'No project ID');
    try {
      const { data } = await apiClient.put(`/projects/${sharedProjectId}`, { status: 'In Progress' });
      return makeResult('project', 'update', true, { status: data.status });
    } catch (err) {
      return makeResult('project', 'update', false, null, err.message);
    }
  });

export const testDeleteProject = async () =>
  timed(async () => {
    if (!sharedProjectId) return makeResult('project', 'delete', false, null, 'No project ID');
    try {
      await apiClient.delete(`/projects/${sharedProjectId}`);
      sharedProjectId = null;
      return makeResult('project', 'delete', true, { deleted: true });
    } catch (err) {
      return makeResult('project', 'delete', false, null, err.message);
    }
  });

// ─── Task Module ──────────────────────────────────────────────────────────────

const ensureProjectForTask = async () => {
  if (sharedProjectId) return;
  try {
    const { data } = await apiClient.post('/projects', {
      name: `[AUTO-TEST-TASK] ${Date.now()}`,
      description: 'Created for task tests',
    });
    sharedProjectId = data._id || data.id;
  } catch (_) {}
};

export const testCreateTask = async () =>
  timed(async () => {
    await ensureProjectForTask();
    if (!sharedProjectId) return makeResult('task', 'create', false, null, 'No project available for task');
    try {
      const { data } = await apiClient.post('/tasks', {
        title: `[AUTO-TEST] Task ${Date.now()}`,
        description: 'Auto-generated task',
        projectId: sharedProjectId,
      });
      sharedTaskId = data._id || data.id;
      return makeResult('task', 'create', true, { id: sharedTaskId });
    } catch (err) {
      return makeResult('task', 'create', false, null, err.message);
    }
  });

export const testGetTasksByProject = async () =>
  timed(async () => {
    if (!sharedProjectId) return makeResult('task', 'getByProject', false, null, 'No project ID');
    try {
      const { data } = await apiClient.get(`/tasks/project/${sharedProjectId}`);
      const count = Array.isArray(data) ? data.length : '?';
      return makeResult('task', 'getByProject', true, { count });
    } catch (err) {
      return makeResult('task', 'getByProject', false, null, err.message);
    }
  });

export const testUpdateTask = async () =>
  timed(async () => {
    if (!sharedTaskId) return makeResult('task', 'update', false, null, 'No task ID');
    try {
      const { data } = await apiClient.put(`/tasks/${sharedTaskId}`, { status: 'in-progress' });
      return makeResult('task', 'update', true, { status: data.status });
    } catch (err) {
      return makeResult('task', 'update', false, null, err.message);
    }
  });

export const testDeleteTask = async () =>
  timed(async () => {
    if (!sharedTaskId) return makeResult('task', 'delete', false, null, 'No task ID');
    try {
      await apiClient.delete(`/tasks/${sharedTaskId}`);
      sharedTaskId = null;
      return makeResult('task', 'delete', true, { deleted: true });
    } catch (err) {
      return makeResult('task', 'delete', false, null, err.message);
    }
  });

// ─── Agent Module ─────────────────────────────────────────────────────────────

const agentTypes = ['planner', 'task', 'risk', 'ethics', 'report'];
export const testAgents = async () =>
  Promise.all(
    agentTypes.map(type =>
      timed(async () => {
        try {
          const { data } = await apiClient.post('/agents/run', {
            type,
            payload: { projectId: sharedProjectId || 'test', timestamp: Date.now() },
          });
          return makeResult('agent', type, true, data);
        } catch (err) {
          return makeResult('agent', type, false, null, err.message);
        }
      })
    )
  );

// ─── Engine Module ────────────────────────────────────────────────────────────

const engineTypes = ['rule', 'scoring', 'dependency', 'replanning'];
export const testEngines = async () =>
  Promise.all(
    engineTypes.map(type =>
      timed(async () => {
        try {
          const { data } = await apiClient.post('/agents/run', {
            type,
            payload: { projectId: sharedProjectId || 'test', timestamp: Date.now() },
          });
          return makeResult('engine', type, true, data);
        } catch (err) {
          return makeResult('engine', type, false, null, err.message);
        }
      })
    )
  );

// ─── Report Module ────────────────────────────────────────────────────────────

export const testCreateReport = async () =>
  timed(async () => {
    try {
      const { data } = await apiClient.post('/reports', {
        project: sharedProjectId || 'test-project',
        title: `[AUTO-TEST] Report ${Date.now()}`,
        content: 'Automated test report generated by test service.',
      });
      return makeResult('report', 'create', true, { id: data._id || data.id });
    } catch (err) {
      return makeResult('report', 'create', false, null, err.message);
    }
  });

// ─── Run All Tests ────────────────────────────────────────────────────────────

/**
 * Run all tests sequentially.
 * @param {object} opts
 * @param {boolean} opts.stopOnFailure - Stop the entire suite on first failure (default: false)
 * @param {function} opts.onResult - Callback invoked after each result for live streaming
 */
export const runAllTests = async ({ stopOnFailure = false, onResult = null } = {}) => {
  const results = [];

  const run = async (label, testFn) => {
    const result = await testFn();
    const normalized = Array.isArray(result) ? result : [result];
    results.push(...normalized);
    if (onResult) normalized.forEach(r => onResult(r));
    return normalized;
  };

  const shouldStop = (batch) => stopOnFailure && batch.some(r => !r.success);

  // 1. Health Check
  const healthBatch = await run('health', testHealth);
  if (shouldStop(healthBatch)) return results;

  // 2. Auth: register → login
  await run('register', testRegister);
  const loginBatch = await run('login', testLogin);
  if (shouldStop(loginBatch)) return results;

  // 3. Projects (full CRUD)
  const createProjectBatch = await run('createProject', testCreateProject);
  if (shouldStop(createProjectBatch)) return results;
  await run('getProjects', testGetProjects);
  await run('getSingleProject', testGetSingleProject);
  await run('updateProject', testUpdateProject);

  // 4. Tasks (CRUD before deleting project)
  const createTaskBatch = await run('createTask', testCreateTask);
  if (shouldStop(createTaskBatch)) return results;
  await run('getTasksByProject', testGetTasksByProject);
  await run('updateTask', testUpdateTask);
  await run('deleteTask', testDeleteTask);

  // 5. Agents & Engines
  await run('agents', testAgents);
  await run('engines', testEngines);

  // 6. Report
  await run('createReport', testCreateReport);

  // 7. Clean up — delete project last
  await run('deleteProject', testDeleteProject);

  return results;
};
